### PR TITLE
Fix small header crash in search results

### PR DESCRIPTION
**Pull request by rubao**
Problem:
image

### CODE REVIEW

**Comment by edmundoa** [comment]
Hi,

Could you explain a bit more what you are trying to achieve there?

**Comment by rubao** [comment]
yes sorry.. I added a screenshot to the description.

**Comment by edmundoa** [comment]
We need you to sign a contributor agreement before merging the changes. Please follow the steps in https://www.graylog.org/contributing-to-graylog/ under the "Pull requests" section.

**Comment by edmundoa** [comment]
Hi @rubao,

Could you please send that CA, so that we can get this change merged? :)

Thank you!

**Pull request closed without merging**
