### PR TITLE
Configurable flexible date converter

### PR DESCRIPTION
**Pull request by joschi**
Add UI option to configure the time zone for the flexible date converter.

Relies on Graylog2/graylog2-server#1166

### CODE REVIEW

**Comment by joschi** [comment]
@edmundoa FYI, this PR actually only contains commit b1a253f09836329c36677c60588339bee219e3c4. No idea why those other 3 commits are shown (as `master` has been updated with those from the `1.1` branch).

**Comment by edmundoa** [comment]
cm-14834-05019ee542beb6

**Comment by edmundoa** [comment]
I couldn't make it work, it looks like we are missing code to include the timezone field into the converter here: https://github.com/Graylog2/graylog2-server/blob/master/graylog2-rest-client/src/main/java/org/graylog2/restclient/models/Extractor.java#L223

Another small thing that I think would help to make it nicer to use is to use a select like in the user forms, so users don't need to think too much about timezone IDs. If you want to do that, you could copy (or extract to a partial) the selector in here: https://github.com/Graylog2/graylog2-web-interface/blob/master/app/views/system/users/new_user.scala.html#L158

**Comment by edmundoa** [comment]
LGTM :+1:

**Pull request merged**
