### PR TITLE
Support changes done in the server by changing class names.

### PR DESCRIPTION
**Pull request by dennisoelkers**

### CODE REVIEW

**Comment by edmundoa** [comment]
Do we really want to get rid of the input buffer info on the node page? Just double-checking :)

**Comment by lennartkoopmann** [comment]
Only 1 build in matrix failed and reason for this was the GitHub downtime. Should be safe to merge.

**Comment by lennartkoopmann** [comment]
Merged because Graylog2/graylog2-server#1077 has been merged and it is depending on this PR. The web interface was broken without merging this.

The changes looked trivial but the removal of the input buffer info on the node page might indeed need an explanation from @dennisoelkers to make sure that it was not accidental.

**Comment by lennartkoopmann** [comment]
Looks like the changes in here are incomplete though. Still getting a lot of errors related to missing models.

**Comment by lennartkoopmann** [comment]
`master` works again

**Pull request merged**
