### PR TITLE
Fixes link to the documentation

### PR DESCRIPTION
**Pull request by cstuder**
Old link: http://docs.graylog.org/en/1.2/pages/users_roles.html
New link: http://docs.graylog.org/en/1.2/pages/users_and_roles.html

### CODE REVIEW

**Comment by cstuder** [comment]
Alternatively you could rename the page here: https://github.com/Graylog2/documentation/blob/master/pages/users_and_roles.rst

**Comment by lennartkoopmann** [comment]
Oh no, this was my mistake when changing the docs, sorry. I will set up a proxy page in the docs next thing. Did not think about links in the web interface when renaming.

**Comment by joschi** [comment]
@cstuder Thanks! I've updated the link in the relevant branches.

**Comment by lennartkoopmann** [comment]
[Fixed](http://docs.graylog.org/en/1.2/pages/users_roles.html). Thanks!

**Pull request closed without merging**
