### PR TITLE
Clean up documentation links

### PR DESCRIPTION
**Pull request by lennartkoopmann**
I cleaned up the documentation links and unified the usage to one helper method instead of the dozens helpers that we had before.

**Important:** This has no effect on react code that might link to docs yet. I'll leave this to somebody with more react experience in #1465.

### CODE REVIEW

**Comment by bernd** [comment]
My idea was to build a `DocsHelper` that looks like this.

```java
package org.graylog2;

import org.graylog2.restclient.lib.Version;

public enum DocsHelper {
    PAGE_DASHBOARD("dashboards.html"),
    PAGE_STREAMS_RUNTIME_LIMIT("streams.html#stream-processing-runtime-limits");

    private final String path;

    DocsHelper(String path) {
        this.path = path;
    }

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer("http://docs.graylog.org/en/")
                .append(Version.VERSION.getBranchName())
                .append("/pages/")
                .append(path);

        return sb.toString();
    }

    public String toLink(String title) {
        final StringBuffer sb = new StringBuffer("<a href=\"")
                .append(toString())
                .append("\" target=\"_blank\">")
                .append(title)
                .append("</a>");

        return sb.toString();
    }
}
```

Using `DocsHelper.PAGE_STREAMS_RUNTIME_LIMIT.toLink("the foo bar")` and `DocsHelper.PAGE_DASHBOARD.toString()` instead of strings makes it easy to change all links in one place and also makes it really easy to find all usages of a link in code and templates.

I think we should use the same thin in the server. I has always been a pain to maintain the documentation links in server and web.

**Comment by kroepke** [comment]
Completely agree with Bernd, let's give them a name and make our lives easier :+1:

**Comment by edmundoa** [comment]
I would also wait to merge any changes on this in the 1.1 branch until 1.1.2 is released, don't want to see broken links just after the release :smile:

**Comment by lennartkoopmann** [comment]
or like that, even better! thanks!

**Comment by bernd** [comment]
I created Graylog2/graylog2-server#1238 to do a similar thing in server.

**Comment by edmundoa** [comment]
I modified the changes Lennart did to use an enum (like Bernd did on Graylog2/graylog2-server#1238). The react code is still unchanged, and will probably take care of it in another PR.

I hope I didn't miss any links, some of them are quite hard to find :)

**Pull request merged**
